serve:
  port: 4001
  browser: false
  endpoint: /

sources:
  - name: GraphQL API
    handler:
      graphql:
        schema: ./src/schema.ts
    transforms:
      - federation:
          types:
            - name: Product
              config:
                key:
                  - fields: "id"
                  - fields: "sku package"
                  - fields: "sku variation { id }"
                resolveReference:
                  queryFieldName: _resolveProduct
                  args:
                    id: "{root.id}"
                    sku: "{root.sku}"
                    package: "{root.package}"
                    variationId: "{root.variation.id}"
                fields:
                  - name: createdBy
                    config:
                      provides:
                        fields: "totalProductsCreated"
                  - name: notes
                    config:
                      tag:
                        name: "internal"
            - name: DeprecatedProduct
              config:
                key:
                  - fields: "sku package"
                resolveReference:
                  queryFieldName: _resolveDeprecatedProduct
                  args:
                    sku: "{root.sku}"
                    package: "{root.package}"
            - name: ProductResearch
              config:
                key:
                  - fields: "study { caseNumber }"
                resolveReference:
                  queryFieldName: _resolveProductResearch
                  args:
                    studyCaseNumber: "{root.study.caseNumber}"
            - name: ProductDimension
              config:
                shareable: true
                fields:
                  - name: unit
                    config:
                      inaccessible: true
            - name: User
              config:
                key:
                  - fields: email
                fields:
                  - name: averageProductsCreatedPerYear
                    config:
                      requires:
                        fields: "totalProductsCreated yearsOfEmployment"
                  - name: email
                    config:
                      external: true
                  - name: name
                    config:
                      override:
                        from: "users"
                  - name: totalProductsCreated
                    config:
                      external: true
                  - name: yearsOfEmployment
                    config:
                      external: true

transforms:
  - filterSchema:
      - Query.!_resolve*

plugins:
  - apolloInlineTrace: {}
